Bumped version from 2.0.1 to 2.1.0.
opensearch-project/alerting-dashboards-plugin pull request #277
Opened 2022-06-22 21:57 UTC by AWSHurneyt

Signed-off-by: AWSHurneyt <hurneyt@amazon.com>

### Description
Bumped version from 2.0.1 to 2.1.0.
 
### Issues Resolved
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/276
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-24 16:34 UTC, lezzago requested changes

2022-06-24 16:34 UTC, lezzago commented on .github/workflows/cypress-workflow.yml
>    OPENSEARCH_DASHBOARDS_VERSION: '2.0'
We need to change this to 2.x

2022-06-24 16:48 UTC, AWSHurneyt commented on .github/workflows/cypress-workflow.yml
>    OPENSEARCH_DASHBOARDS_VERSION: '2.0'
Updated.

2022-06-24 17:24 UTC, lezzago approved these changes

2022-06-24 17:28 UTC, rishabhmaurya approved these changes

2022-06-24 17:28 UTC, merged

2022-06-24 20:09 UTC, bowenlan-amzn commented
Seems we miss to change the dashboard version in UT workflow https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/.github/workflows/unit-tests-workflow.yml#L14

2022-06-27 17:35 UTC, AWSHurneyt commented
> Seems we miss to change the dashboard version in UT workflow https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/.github/workflows/unit-tests-workflow.yml#L14

Thank you for catching this! I adjusted the branch referenced by this file in [this PR](https://github.com/opensearch-project/alerting-dashboards-plugin/pull/278.)